// Code generated by ent, DO NOT EDIT.

package dip

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/enums"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/persistence/ent/db/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DIP {
	return predicate.DIP(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DIP {
	return predicate.DIP(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DIP {
	return predicate.DIP(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DIP {
	return predicate.DIP(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DIP {
	return predicate.DIP(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DIP {
	return predicate.DIP(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DIP {
	return predicate.DIP(sql.FieldLTE(FieldID, id))
}

// UUID applies equality check predicate on the "uuid" field. It's identical to UUIDEQ.
func UUID(v uuid.UUID) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldUUID, v))
}

// DocKey applies equality check predicate on the "doc_key" field. It's identical to DocKeyEQ.
func DocKey(v string) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldDocKey, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldCreatedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldCompletedAt, v))
}

// ObjectKey applies equality check predicate on the "object_key" field. It's identical to ObjectKeyEQ.
func ObjectKey(v string) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldObjectKey, v))
}

// UUIDEQ applies the EQ predicate on the "uuid" field.
func UUIDEQ(v uuid.UUID) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldUUID, v))
}

// UUIDNEQ applies the NEQ predicate on the "uuid" field.
func UUIDNEQ(v uuid.UUID) predicate.DIP {
	return predicate.DIP(sql.FieldNEQ(FieldUUID, v))
}

// UUIDIn applies the In predicate on the "uuid" field.
func UUIDIn(vs ...uuid.UUID) predicate.DIP {
	return predicate.DIP(sql.FieldIn(FieldUUID, vs...))
}

// UUIDNotIn applies the NotIn predicate on the "uuid" field.
func UUIDNotIn(vs ...uuid.UUID) predicate.DIP {
	return predicate.DIP(sql.FieldNotIn(FieldUUID, vs...))
}

// UUIDGT applies the GT predicate on the "uuid" field.
func UUIDGT(v uuid.UUID) predicate.DIP {
	return predicate.DIP(sql.FieldGT(FieldUUID, v))
}

// UUIDGTE applies the GTE predicate on the "uuid" field.
func UUIDGTE(v uuid.UUID) predicate.DIP {
	return predicate.DIP(sql.FieldGTE(FieldUUID, v))
}

// UUIDLT applies the LT predicate on the "uuid" field.
func UUIDLT(v uuid.UUID) predicate.DIP {
	return predicate.DIP(sql.FieldLT(FieldUUID, v))
}

// UUIDLTE applies the LTE predicate on the "uuid" field.
func UUIDLTE(v uuid.UUID) predicate.DIP {
	return predicate.DIP(sql.FieldLTE(FieldUUID, v))
}

// DocKeyEQ applies the EQ predicate on the "doc_key" field.
func DocKeyEQ(v string) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldDocKey, v))
}

// DocKeyNEQ applies the NEQ predicate on the "doc_key" field.
func DocKeyNEQ(v string) predicate.DIP {
	return predicate.DIP(sql.FieldNEQ(FieldDocKey, v))
}

// DocKeyIn applies the In predicate on the "doc_key" field.
func DocKeyIn(vs ...string) predicate.DIP {
	return predicate.DIP(sql.FieldIn(FieldDocKey, vs...))
}

// DocKeyNotIn applies the NotIn predicate on the "doc_key" field.
func DocKeyNotIn(vs ...string) predicate.DIP {
	return predicate.DIP(sql.FieldNotIn(FieldDocKey, vs...))
}

// DocKeyGT applies the GT predicate on the "doc_key" field.
func DocKeyGT(v string) predicate.DIP {
	return predicate.DIP(sql.FieldGT(FieldDocKey, v))
}

// DocKeyGTE applies the GTE predicate on the "doc_key" field.
func DocKeyGTE(v string) predicate.DIP {
	return predicate.DIP(sql.FieldGTE(FieldDocKey, v))
}

// DocKeyLT applies the LT predicate on the "doc_key" field.
func DocKeyLT(v string) predicate.DIP {
	return predicate.DIP(sql.FieldLT(FieldDocKey, v))
}

// DocKeyLTE applies the LTE predicate on the "doc_key" field.
func DocKeyLTE(v string) predicate.DIP {
	return predicate.DIP(sql.FieldLTE(FieldDocKey, v))
}

// DocKeyContains applies the Contains predicate on the "doc_key" field.
func DocKeyContains(v string) predicate.DIP {
	return predicate.DIP(sql.FieldContains(FieldDocKey, v))
}

// DocKeyHasPrefix applies the HasPrefix predicate on the "doc_key" field.
func DocKeyHasPrefix(v string) predicate.DIP {
	return predicate.DIP(sql.FieldHasPrefix(FieldDocKey, v))
}

// DocKeyHasSuffix applies the HasSuffix predicate on the "doc_key" field.
func DocKeyHasSuffix(v string) predicate.DIP {
	return predicate.DIP(sql.FieldHasSuffix(FieldDocKey, v))
}

// DocKeyEqualFold applies the EqualFold predicate on the "doc_key" field.
func DocKeyEqualFold(v string) predicate.DIP {
	return predicate.DIP(sql.FieldEqualFold(FieldDocKey, v))
}

// DocKeyContainsFold applies the ContainsFold predicate on the "doc_key" field.
func DocKeyContainsFold(v string) predicate.DIP {
	return predicate.DIP(sql.FieldContainsFold(FieldDocKey, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v enums.DIPStatus) predicate.DIP {
	vc := v
	return predicate.DIP(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v enums.DIPStatus) predicate.DIP {
	vc := v
	return predicate.DIP(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...enums.DIPStatus) predicate.DIP {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.DIP(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...enums.DIPStatus) predicate.DIP {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.DIP(sql.FieldNotIn(FieldStatus, v...))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.DIP {
	return predicate.DIP(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.DIP {
	return predicate.DIP(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.DIP {
	return predicate.DIP(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.DIP {
	return predicate.DIP(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.DIP {
	return predicate.DIP(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.DIP {
	return predicate.DIP(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.DIP {
	return predicate.DIP(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.DIP {
	return predicate.DIP(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.DIP {
	return predicate.DIP(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.DIP {
	return predicate.DIP(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.DIP {
	return predicate.DIP(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.DIP {
	return predicate.DIP(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.DIP {
	return predicate.DIP(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.DIP {
	return predicate.DIP(sql.FieldContainsFold(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldLTE(FieldCreatedAt, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.DIP {
	return predicate.DIP(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.DIP {
	return predicate.DIP(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.DIP {
	return predicate.DIP(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.DIP {
	return predicate.DIP(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.DIP {
	return predicate.DIP(sql.FieldNotNull(FieldCompletedAt))
}

// ObjectKeyEQ applies the EQ predicate on the "object_key" field.
func ObjectKeyEQ(v string) predicate.DIP {
	return predicate.DIP(sql.FieldEQ(FieldObjectKey, v))
}

// ObjectKeyNEQ applies the NEQ predicate on the "object_key" field.
func ObjectKeyNEQ(v string) predicate.DIP {
	return predicate.DIP(sql.FieldNEQ(FieldObjectKey, v))
}

// ObjectKeyIn applies the In predicate on the "object_key" field.
func ObjectKeyIn(vs ...string) predicate.DIP {
	return predicate.DIP(sql.FieldIn(FieldObjectKey, vs...))
}

// ObjectKeyNotIn applies the NotIn predicate on the "object_key" field.
func ObjectKeyNotIn(vs ...string) predicate.DIP {
	return predicate.DIP(sql.FieldNotIn(FieldObjectKey, vs...))
}

// ObjectKeyGT applies the GT predicate on the "object_key" field.
func ObjectKeyGT(v string) predicate.DIP {
	return predicate.DIP(sql.FieldGT(FieldObjectKey, v))
}

// ObjectKeyGTE applies the GTE predicate on the "object_key" field.
func ObjectKeyGTE(v string) predicate.DIP {
	return predicate.DIP(sql.FieldGTE(FieldObjectKey, v))
}

// ObjectKeyLT applies the LT predicate on the "object_key" field.
func ObjectKeyLT(v string) predicate.DIP {
	return predicate.DIP(sql.FieldLT(FieldObjectKey, v))
}

// ObjectKeyLTE applies the LTE predicate on the "object_key" field.
func ObjectKeyLTE(v string) predicate.DIP {
	return predicate.DIP(sql.FieldLTE(FieldObjectKey, v))
}

// ObjectKeyContains applies the Contains predicate on the "object_key" field.
func ObjectKeyContains(v string) predicate.DIP {
	return predicate.DIP(sql.FieldContains(FieldObjectKey, v))
}

// ObjectKeyHasPrefix applies the HasPrefix predicate on the "object_key" field.
func ObjectKeyHasPrefix(v string) predicate.DIP {
	return predicate.DIP(sql.FieldHasPrefix(FieldObjectKey, v))
}

// ObjectKeyHasSuffix applies the HasSuffix predicate on the "object_key" field.
func ObjectKeyHasSuffix(v string) predicate.DIP {
	return predicate.DIP(sql.FieldHasSuffix(FieldObjectKey, v))
}

// ObjectKeyIsNil applies the IsNil predicate on the "object_key" field.
func ObjectKeyIsNil() predicate.DIP {
	return predicate.DIP(sql.FieldIsNull(FieldObjectKey))
}

// ObjectKeyNotNil applies the NotNil predicate on the "object_key" field.
func ObjectKeyNotNil() predicate.DIP {
	return predicate.DIP(sql.FieldNotNull(FieldObjectKey))
}

// ObjectKeyEqualFold applies the EqualFold predicate on the "object_key" field.
func ObjectKeyEqualFold(v string) predicate.DIP {
	return predicate.DIP(sql.FieldEqualFold(FieldObjectKey, v))
}

// ObjectKeyContainsFold applies the ContainsFold predicate on the "object_key" field.
func ObjectKeyContainsFold(v string) predicate.DIP {
	return predicate.DIP(sql.FieldContainsFold(FieldObjectKey, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DIP) predicate.DIP {
	return predicate.DIP(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DIP) predicate.DIP {
	return predicate.DIP(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DIP) predicate.DIP {
	return predicate.DIP(sql.NotPredicates(p))
}
