package design

import . "goa.design/goa/v3/dsl" //nolint:staticcheck

var BearerAuth = BearerSecurity("bearer", func() {
	Description(
		"Authenticate with an access token supplied as Authorization: Bearer [token]. " +
			"Clients obtain tokens from an external OIDC provider.",
	)
})

var _ = API("DIPs", func() {
	Title("DIPs API")
	Description("The DIPs API is used to request DIP creation and retrieve DIP details.")
	Version("0.1.0")
})

var DIPID = Type("DIPID", String, func() {
	Description("DIPID uniquely identifies a DIP.")
	Format(FormatUUID)
	Example("3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb")
})

var DocKey = Type("DocKey", String, func() {
	Description("DocKey is the document key used to create a DIP.")
	MinLength(1)
	Example("CH-000001")
})

var DIPStatus = Type("DIPStatus", String, func() {
	Description("DIPStatus represents the current status of a DIP.")
	Enum("queued", "in progress", "done", "failed")
	Example("done")
})

var DateTime = Type("DateTime", String, func() {
	Description("DateTime represents an RFC3339 timestamp.")
	Format(FormatDateTime)
	Example("2026-05-27T15:04:05Z")
})

var ObjectKey = Type("ObjectKey", String, func() {
	Description("ObjectKey represents the object store key for a DIP.")
	MinLength(1)
	Example("dips/3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb.zip")
})

var ProblemDetails = Type("ProblemDetails", func() {
	Description("ProblemDetails represents an RFC 9457 problem details object.")
	Attribute("type", String, "The type field contains a URI reference that identifies the problem type.", func() {
		Format(FormatURI)
		Default("about:blank")
		Example("about:blank")
	})
	Attribute("title", String, "The title field contains a short, human-readable summary of the problem type.", func() {
		Example("Invalid request parameters.")
	})
	Attribute("detail", String, "The detail field contains a human-readable explanation specific to this problem occurrence.", func() {
		Example("The request body is missing the docKey field.")
	})
	Attribute("status", Int32, "The status field contains the HTTP status code generated by the origin server.", func() {
		Example(400)
	})
	Attribute("instance", String, "The instance field contains a URI reference that identifies this problem occurrence.", func() {
		// The instance field is optional in RFC 9457, but we include it in the
		// schema for completeness. For now, we don't generate instance values in
		// the implementation, so we remove it from the example to avoid confusion.
		Meta("openapi:example", "false")
	})
	Required("type", "title", "status", "detail")
})

var ParamError = Type("ParamError", func() {
	Description("ParamError represents an error related to a specific request parameter.")
	Field(1, "detail", String, "The detail field describes the error.", func() {
		Example("The 'docKey' field is required.")
	})
	Field(2, "parameter", String, "The parameter field contains the name of the parameter that caused the error.", func() {
		Example("docKey")
	})
})

var MissingReqParamError = Type("MissingReqParamError", func() {
	Description("One or more request parameters are missing.")

	Reference(ProblemDetails)

	// Attributes inherited from ProblemDetails.
	Attribute("title", func() {
		Example("Missing Request Parameter")
	})
	Attribute("detail", func() {
		Example("One or more request parameters are missing.")
	})
	Attribute("status", func() {
		Example(400)
	})

	// Override the type attribute with a default value specific to this error
	// type.
	Attribute("type", func() {
		Default("https://problems-registry.smartbear.com/invalid-request-body")
		Example("https://problems-registry.smartbear.com/missing-request-parameter")
	})

	// Additional attributes specific to this error type.
	Attribute(
		"code",
		String,
		"The code field contains a machine-readable error code.",
		func() {
			Example("400-03")
		},
	)
	Attribute(
		"errors",
		ArrayOf(ParamError),
		"A list of parameter errors.",
		func() {
			Example([]Val{
				{
					"detail":    "The 'docKey' field is required.",
					"parameter": "docKey",
				},
			})
		},
	)

	Example(func() {
		Value(Val{
			"code":   "400-03",
			"detail": "The request is missing an expected query or path parameter.",
			"status": 400,
			"errors": []Val{
				{
					"detail":    "The 'docKey' field is required.",
					"parameter": "docKey",
				},
			},
			"title": "Missing Request Parameter",
			"type":  "https://problems-registry.smartbear.com/missing-request-parameter",
		})
	})
})

var InternalError = Type("InternalError", func() {
	Extend(ProblemDetails)
	Description("An internal server error occurred.")
})

var NotFoundError = Type("NotFoundError", func() {
	Extend(ProblemDetails)
	Description("The requested resource is not found.")
})

var UnauthorizedError = Type("UnauthorizedError", func() {
	Extend(ProblemDetails)
	Description("The request is unauthorized due to missing or invalid authentication credentials.")
})

var CreateDIPResult = Type("CreateDIPResult", func() {
	Description("CreateDIPResult contains the result of a DIP creation request.")
	Field(1, "id", DIPID, "The id field contains the identifier assigned to the DIP.")
	Required("id")
})

var DIP = Type("DIP", func() {
	Description("DIP represents the details of a DIP.")
	Field(1, "id", DIPID, "The id field uniquely identifies the DIP.")
	Field(2, "docKey", DocKey, "The docKey field contains the document key used to create the DIP.")
	Field(3, "status", DIPStatus, "The status field contains the current DIP status.")
	Field(4, "created_at", DateTime, "The created_at field contains the time when the DIP was requested.")
	Field(5, "started_at", DateTime, "The started_at field contains the time when DIP processing started.")
	Field(6, "completed_at", DateTime, "The completed_at field contains the time when DIP processing completed.")
	Field(7, "object_key", ObjectKey, "The object_key field contains the object store key for the completed DIP.")
	Required("id", "docKey", "status", "created_at")
})

var _ = Service("DIPs", func() {
	Description("The DIPs service requests DIP creation and retrieves DIP details.")
	Security(BearerAuth)

	Error("missing_req_param", MissingReqParamError)
	Error("internal", InternalError)
	Error("unauthorized", UnauthorizedError)

	HTTP(func() {
		errorResponse("missing_req_param", StatusBadRequest)
		errorResponse("internal", StatusInternalServerError)
		errorResponse("unauthorized", StatusUnauthorized)
	})

	Method("create", func() {
		Description("The create method requests DIP creation for a document key.")
		Payload(func() {
			BearerTokenField(1, "token", String, "The token field contains the OIDC bearer token.")
			Field(2, "docKey", DocKey, "The docKey field contains the document key used to create the DIP.")
			Required("token", "docKey")
		})
		Result(CreateDIPResult)

		HTTP(func() {
			POST("/dips")
			Header("token:Authorization")
			Body(func() {
				Attribute("docKey")
			})
			Response(StatusAccepted)
		})
	})

	Method("show", func() {
		Description("The show method retrieves DIP details.")
		Payload(func() {
			BearerTokenField(1, "token", String, "The token field contains the OIDC bearer token.")
			Field(2, "id", DIPID, "The id field contains the DIP identifier.")
			Required("token", "id")
		})
		Result(DIP)

		Error("not_found", NotFoundError)

		HTTP(func() {
			GET("/dips/{id}")
			Header("token:Authorization")
			Response(StatusOK)
			errorResponse("not_found", StatusNotFound)
		})
	})
})

func problemDetailsExample(typ, title, detail string, status int32) {
	Example(func() {
		Value(Val{
			"type":   typ,
			"title":  title,
			"detail": detail,
			"status": status,
		})
	})
}

func errorResponse(errorName string, status int) {
	Response(errorName, status, func() {
		ContentType("application/problem+json")
	})
}
