package design

import . "goa.design/goa/v3/dsl" //nolint:staticcheck

var BearerAuth = BearerSecurity("bearer", func() {
	Description(
		"Authenticate with an access token supplied as Authorization: Bearer [token]. " +
			"Clients obtain tokens from an external OIDC provider.",
	)
})

var _ = API("DIPs", func() {
	Title("DIPs API")
	Description("API used to request DIP creation and poll DIP details.")
	Version("0.1.0")
})

var DIPID = Type("DIPID", String, func() {
	Description("DIP identifier.")
	Format(FormatUUID)
	Example("3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb")
})

var DocKey = Type("DocKey", String, func() {
	Description("Document key.")
	MinLength(1)
	Example("CH-000001")
})

var DIPStatus = Type("DIPStatus", String, func() {
	Description("Current DIP status.")
	Enum("queued", "in progress", "done", "failed")
	Example("done")
})

var DateTime = Type("DateTime", String, func() {
	Description("RFC3339 timestamp.")
	Format(FormatDateTime)
	Example("2026-05-27T15:04:05Z")
})

var ObjectKey = Type("ObjectKey", String, func() {
	Description("Object store key for the completed DIP.")
	MinLength(1)
	Example("dips/3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb.zip")
})

const (
	// RFC 9457 "type" values double as Goa error names. Goa uses the
	// ErrorName field value to select the HTTP response mapping when a single
	// custom error type is reused for multiple errors, so these constants must
	// match the Error and Response names below.
	problemTypeUnauthorized = "/problems/unauthorized"
	problemTypeNotValid     = "/problems/not-valid"
	problemTypeNotFound     = "/problems/not-found"
	problemTypeInternal     = "/problems/internal-error"
)

var ProblemDetails = Type("ProblemDetails", func() {
	Description("RFC 9457 problem details object.")
	// Use the RFC 9457 "type" member as Goa's error discriminator instead of
	// adding a private "name" field. This keeps the wire body and OpenAPI schema
	// to the standard problem details fields while still letting Goa route
	// shared errors to distinct HTTP status codes.
	ErrorName("type", String, "URI reference that identifies the problem type.", func() {
		Format(FormatURI)
		Enum(problemTypeUnauthorized, problemTypeNotValid, problemTypeNotFound, problemTypeInternal)
		Example(problemTypeNotValid)
	})
	Attribute("title", String, "Short, human-readable summary of the problem type.", func() {
		Example("Invalid request parameters.")
	})
	Attribute("detail", String, "Human-readable explanation specific to this problem occurrence.", func() {
		Example("The request body is missing the docKey field.")
	})
	Attribute("status", Int, "HTTP status code generated by the origin server.", func() {
		Example(400)
	})
	Attribute("instance", String, "URI reference that identifies this problem occurrence.", func() {
		// The instance field is optional in RFC 9457, but we include it in the
		// schema for completeness. For now, we don't generate instance values in
		// the implementation, so we remove it from the example to avoid confusion.
		Meta("openapi:example", "false")
	})
	Required("type", "title", "status", "detail")
})

var CreateDIPResult = Type("CreateDIPResult", func() {
	Description("DIP creation request result.")
	Field(1, "id", DIPID, "Identifier assigned to the DIP.")
	Required("id")
})

var DIP = Type("DIP", func() {
	Description("DIP details.")
	Field(1, "id", DIPID, "DIP identifier.")
	Field(2, "docKey", DocKey, "Document key used to create the DIP.")
	Field(3, "status", DIPStatus, "Current DIP status.")
	Field(4, "created_at", DateTime, "Time when the DIP was requested.")
	Field(5, "started_at", DateTime, "Time when DIP processing started.")
	Field(6, "completed_at", DateTime, "Time when DIP processing completed.")
	Field(7, "object_key", ObjectKey, "Object store key for the completed DIP.")
	Required("id", "docKey", "status", "created_at")
})

var _ = Service("DIPs", func() {
	Description("Requests DIP creation and reports DIP details.")
	Security(BearerAuth)

	Error(problemTypeNotValid, ProblemDetails, "Invalid request parameters.", func() {
		problemDetailsExample(
			problemTypeNotValid,
			"Invalid request parameters.",
			"The request body is missing the docKey field.",
			StatusBadRequest,
		)
	})
	Error(problemTypeUnauthorized, ProblemDetails, "Missing or invalid bearer token.", func() {
		problemDetailsExample(
			problemTypeUnauthorized,
			"Invalid bearer token.",
			"The Authorization header is missing or invalid.",
			StatusUnauthorized,
		)
	})
	Error(problemTypeNotFound, ProblemDetails, "DIP not found.", func() {
		problemDetailsExample(
			problemTypeNotFound,
			"DIP not found.",
			"The requested DIP does not exist.",
			StatusNotFound,
		)
	})
	Error(problemTypeInternal, ProblemDetails, "Unexpected server error.", func() {
		problemDetailsExample(
			problemTypeInternal,
			"Unexpected server error.",
			"The DIP request could not be processed.",
			StatusInternalServerError,
		)
	})

	HTTP(func() {
		Response(problemTypeUnauthorized, StatusUnauthorized, problemDetailsResponse)
		Response(problemTypeInternal, StatusInternalServerError, problemDetailsResponse)
	})

	Method("create", func() {
		Description("Request DIP creation for a document key.")
		Payload(func() {
			BearerTokenField(1, "token", String, "OIDC bearer token.")
			Field(2, "docKey", DocKey, "Document key used to create the DIP.")
			Required("token", "docKey")
		})
		Result(CreateDIPResult)

		HTTP(func() {
			POST("/dips")
			Header("token:Authorization")
			Body(func() {
				Attribute("docKey")
			})
			Response(StatusAccepted)
			Response(problemTypeNotValid, StatusBadRequest, problemDetailsResponse)
		})
	})

	Method("show", func() {
		Description("Get DIP details.")
		Payload(func() {
			BearerTokenField(1, "token", String, "OIDC bearer token.")
			Field(2, "id", DIPID, "DIP identifier.")
			Required("token", "id")
		})
		Result(DIP)

		HTTP(func() {
			GET("/dips/{id}")
			Header("token:Authorization")
			Response(StatusOK)
			Response(problemTypeNotFound, StatusNotFound, problemDetailsResponse)
		})
	})
})

func problemDetailsExample(typ, title, detail string, status int) {
	Example(func() {
		Value(Val{
			"type":   typ,
			"title":  title,
			"detail": detail,
			"status": status,
		})
	})
}

func problemDetailsResponse() {
	// The response body is inferred from ProblemDetails, and this helper only switches
	// the media type from Goa's default JSON error response to RFC 9457 problem+json.
	ContentType("application/problem+json")
}
