// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package enums

import (
	"fmt"
	"strings"
)

const (
	DIPStatusQueued     DIPStatus = "queued"
	DIPStatusInProgress DIPStatus = "in progress"
	DIPStatusDone       DIPStatus = "done"
	DIPStatusFailed     DIPStatus = "failed"
)

var ErrInvalidDIPStatus = fmt.Errorf("not a valid DIPStatus, try [%s]", strings.Join(_DIPStatusNames, ", "))

var _DIPStatusNames = []string{
	string(DIPStatusQueued),
	string(DIPStatusInProgress),
	string(DIPStatusDone),
	string(DIPStatusFailed),
}

// DIPStatusNames returns a list of possible string values of DIPStatus.
func DIPStatusNames() []string {
	tmp := make([]string, len(_DIPStatusNames))
	copy(tmp, _DIPStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x DIPStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DIPStatus) IsValid() bool {
	_, err := ParseDIPStatus(string(x))
	return err == nil
}

var _DIPStatusValue = map[string]DIPStatus{
	"queued":      DIPStatusQueued,
	"in progress": DIPStatusInProgress,
	"done":        DIPStatusDone,
	"failed":      DIPStatusFailed,
}

// ParseDIPStatus attempts to convert a string to a DIPStatus.
func ParseDIPStatus(name string) (DIPStatus, error) {
	if x, ok := _DIPStatusValue[name]; ok {
		return x, nil
	}
	return DIPStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidDIPStatus)
}

// Values implements the entgo.io/ent/schema/field EnumValues interface.
func (x DIPStatus) Values() []string {
	return DIPStatusNames()
}

// DIPStatusInterfaces returns an interface list of possible values of DIPStatus.
func DIPStatusInterfaces() []interface{} {
	var tmp []interface{}
	for _, v := range _DIPStatusNames {
		tmp = append(tmp, v)
	}
	return tmp
}

// ParseDIPStatusWithDefault attempts to convert a string to a ContentType.
// It returns the default value if name is empty.
func ParseDIPStatusWithDefault(name string) (DIPStatus, error) {
	if name == "" {
		return _DIPStatusValue[_DIPStatusNames[0]], nil
	}
	if x, ok := _DIPStatusValue[name]; ok {
		return x, nil
	}
	var e DIPStatus
	return e, fmt.Errorf("%s is not a valid DIPStatus, try [%s]", name, strings.Join(_DIPStatusNames, ", "))
}

// NormalizeDIPStatus attempts to parse a and normalize string as content type.
// It returns the input untouched if name fails to be parsed.
// Example:
//
//	"enUM" will be normalized (if possible) to "Enum"
func NormalizeDIPStatus(name string) string {
	res, err := ParseDIPStatus(name)
	if err != nil {
		return name
	}
	return res.String()
}
