package client

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"

	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/datatypes"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/persistence"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/persistence/ent/db/dip"
)

// CreateDIP creates and persists a new DIP using the values from d, then
// updates d with the values stored in the database.
//
// The input DIP DBID and CreatedAt values are ignored. DBID is generated by
// the persistence implementation and CreatedAt is set to the current time.
func (c *client) CreateDIP(ctx context.Context, d *datatypes.DIP) error {
	if d.UUID == uuid.Nil {
		return newRequiredFieldError("UUID")
	}
	if d.DocKey == "" {
		return newRequiredFieldError("DocKey")
	}

	q := c.ent.DIP.Create().
		SetUUID(d.UUID).
		SetDocKey(d.DocKey).
		SetStatus(d.Status).
		SetCreatedAt(time.Now())

	if d.ErrorMessage != "" {
		q.SetErrorMessage(d.ErrorMessage)
	}
	if !d.StartedAt.IsZero() {
		q.SetStartedAt(d.StartedAt)
	}
	if !d.CompletedAt.IsZero() {
		q.SetCompletedAt(d.CompletedAt)
	}
	if d.ObjectKey != "" {
		q.SetObjectKey(d.ObjectKey)
	}

	dbd, err := q.Save(ctx)
	if err != nil {
		return newDBErrorWithDetails(err, "create DIP")
	}

	*d = *datatypes.NewDIP(dbd)

	return nil
}

// ReadDIP returns the DIP identified by id.
func (c *client) ReadDIP(ctx context.Context, id uuid.UUID) (*datatypes.DIP, error) {
	dbd, err := c.ent.DIP.Query().Where(dip.UUID(id)).Only(ctx)
	if err != nil {
		return nil, newDBError(err)
	}

	return datatypes.NewDIP(dbd), nil
}

// UpdateDIP updates the persisted DIP identified by id using updater and
// returns the updated DIP.
//
// DBID, UUID, DocKey, and CreatedAt cannot be updated with this method.
func (c *client) UpdateDIP(
	ctx context.Context,
	id uuid.UUID,
	updater persistence.DIPUpdater,
) (*datatypes.DIP, error) {
	tx, err := c.ent.BeginTx(ctx, nil)
	if err != nil {
		return nil, newDBError(err)
	}

	dbd, err := tx.DIP.Query().Where(dip.UUID(id)).Only(ctx)
	if err != nil {
		return nil, rollback(tx, newDBError(err))
	}

	dbID := dbd.ID

	up, err := updater(datatypes.NewDIP(dbd))
	if err != nil {
		return nil, rollback(tx, newUpdaterError(err))
	}

	q := tx.DIP.UpdateOneID(dbID)

	if up.Status.IsValid() {
		q.SetStatus(up.Status)
	}
	if up.ErrorMessage != "" {
		q.SetErrorMessage(up.ErrorMessage)
	}
	if !up.StartedAt.IsZero() {
		q.SetStartedAt(up.StartedAt)
	}
	if !up.CompletedAt.IsZero() {
		q.SetCompletedAt(up.CompletedAt)
	}
	if up.ObjectKey != "" {
		q.SetObjectKey(up.ObjectKey)
	}

	dbd, err = q.Save(ctx)
	if err != nil {
		return nil, rollback(tx, newDBError(err))
	}
	if err = tx.Commit(); err != nil {
		return nil, rollback(tx, newDBError(err))
	}

	return datatypes.NewDIP(dbd), nil
}

// DeleteDIP deletes the persisted DIP identified by id.
func (c *client) DeleteDIP(ctx context.Context, id uuid.UUID) error {
	n, err := c.ent.DIP.Delete().Where(dip.UUID(id)).Exec(ctx)
	if err != nil {
		return newDBErrorWithDetails(err, "delete DIP")
	}
	if n == 0 {
		return fmt.Errorf("%w: %s", persistence.ErrNotFound, "db: dip not found: delete DIP")
	}

	return nil
}
