swagger: "2.0"
info:
    title: DIPs API
    description: The DIPs API is used to request DIP creation and retrieve DIP details.
    version: 0.1.0
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /dips:
        post:
            tags:
                - DIPs
            summary: create DIPs
            description: The create method requests DIP creation for a document key.
            operationId: DIPs#create
            parameters:
                - name: object
                  in: body
                  required: true
                  schema:
                    type: object
                    properties:
                        docKey:
                            type: string
                            description: The docKey field contains the document key used to create the DIP.
                            example: CH-000001
                            minLength: 1
            responses:
                "202":
                    description: Accepted response.
                    schema:
                        $ref: '#/definitions/CreateDIPResult'
                        required:
                            - id
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/MissingReqParamError'
                        required:
                            - type
                            - title
                            - status
                            - detail
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - type
                            - title
                            - status
                            - detail
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalError'
                        required:
                            - type
                            - title
                            - status
                            - detail
            schemes:
                - http
            security:
                - bearer_header_Authorization: []
    /dips/{id}:
        get:
            tags:
                - DIPs
            summary: show DIPs
            description: The show method retrieves DIP details.
            operationId: DIPs#show
            parameters:
                - name: id
                  in: path
                  description: DIPID uniquely identifies a DIP.
                  required: true
                  type: string
                  format: uuid
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/DIP'
                        required:
                            - id
                            - docKey
                            - status
                            - created_at
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/MissingReqParamError'
                        required:
                            - type
                            - title
                            - status
                            - detail
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/UnauthorizedError'
                        required:
                            - type
                            - title
                            - status
                            - detail
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/NotFoundError'
                        required:
                            - type
                            - title
                            - status
                            - detail
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/InternalError'
                        required:
                            - type
                            - title
                            - status
                            - detail
            schemes:
                - http
            security:
                - bearer_header_Authorization: []
definitions:
    CreateDIPResult:
        title: CreateDIPResult
        type: object
        properties:
            id:
                type: string
                description: The id field contains the identifier assigned to the DIP.
                example: 3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb
                format: uuid
        example:
            id: 3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb
        required:
            - id
    DIP:
        title: DIP
        type: object
        properties:
            completed_at:
                type: string
                description: The completed_at field contains the time when DIP processing completed.
                example: "2026-05-27T15:04:05Z"
                format: date-time
            created_at:
                type: string
                description: The created_at field contains the time when the DIP was requested.
                example: "2026-05-27T15:04:05Z"
                format: date-time
            docKey:
                type: string
                description: The docKey field contains the document key used to create the DIP.
                example: CH-000001
                minLength: 1
            id:
                type: string
                description: The id field uniquely identifies the DIP.
                example: 3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb
                format: uuid
            object_key:
                type: string
                description: The object_key field contains the object store key for the completed DIP.
                example: dips/3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb.zip
                minLength: 1
            started_at:
                type: string
                description: The started_at field contains the time when DIP processing started.
                example: "2026-05-27T15:04:05Z"
                format: date-time
            status:
                type: string
                description: The status field contains the current DIP status.
                example: done
                enum:
                    - queued
                    - in progress
                    - done
                    - failed
        example:
            completed_at: "2026-05-27T15:04:05Z"
            created_at: "2026-05-27T15:04:05Z"
            docKey: CH-000001
            id: 3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb
            object_key: dips/3f38d6f4-7b19-4db8-8d7d-693b84a9a2fb.zip
            started_at: "2026-05-27T15:04:05Z"
            status: done
        required:
            - id
            - docKey
            - status
            - created_at
    InternalError:
        title: InternalError
        type: object
        properties:
            detail:
                type: string
                description: The detail field contains a human-readable explanation specific to this problem occurrence.
                example: The request body is missing the docKey field.
            instance:
                type: string
                description: The instance field contains a URI reference that identifies this problem occurrence.
            status:
                type: integer
                description: The status field contains the HTTP status code generated by the origin server.
                example: 400
                format: int32
            title:
                type: string
                description: The title field contains a short, human-readable summary of the problem type.
                example: Invalid request parameters.
            type:
                type: string
                description: The type field contains a URI reference that identifies the problem type.
                default: about:blank
                example: about:blank
                format: uri
        example:
            detail: The request body is missing the docKey field.
            status: 400
            title: Invalid request parameters.
            type: about:blank
        required:
            - type
            - title
            - status
            - detail
    MissingReqParamError:
        title: MissingReqParamError
        type: object
        properties:
            code:
                type: string
                description: The code field contains a machine-readable error code.
                example: 400-03
            detail:
                type: string
                description: The detail field contains a human-readable explanation specific to this problem occurrence.
                example: One or more request parameters are missing.
            errors:
                type: array
                items:
                    $ref: '#/definitions/ParamError'
                description: A list of parameter errors.
                example:
                    - detail: The 'docKey' field is required.
                      parameter: docKey
            status:
                type: integer
                description: The status field contains the HTTP status code generated by the origin server.
                example: 400
                format: int32
            title:
                type: string
                description: The title field contains a short, human-readable summary of the problem type.
                example: Missing Request Parameter
            type:
                type: string
                description: The type field contains a URI reference that identifies the problem type.
                default: https://problems-registry.smartbear.com/invalid-request-body
                example: https://problems-registry.smartbear.com/missing-request-parameter
                format: uri
        example:
            code: 400-03
            detail: The request is missing an expected query or path parameter.
            errors:
                - detail: The 'docKey' field is required.
                  parameter: docKey
            status: 400
            title: Missing Request Parameter
            type: https://problems-registry.smartbear.com/missing-request-parameter
        required:
            - type
            - title
            - status
            - detail
    NotFoundError:
        title: NotFoundError
        type: object
        properties:
            detail:
                type: string
                description: The detail field contains a human-readable explanation specific to this problem occurrence.
                example: The request body is missing the docKey field.
            instance:
                type: string
                description: The instance field contains a URI reference that identifies this problem occurrence.
            status:
                type: integer
                description: The status field contains the HTTP status code generated by the origin server.
                example: 400
                format: int32
            title:
                type: string
                description: The title field contains a short, human-readable summary of the problem type.
                example: Invalid request parameters.
            type:
                type: string
                description: The type field contains a URI reference that identifies the problem type.
                default: about:blank
                example: about:blank
                format: uri
        example:
            detail: The request body is missing the docKey field.
            status: 400
            title: Invalid request parameters.
            type: about:blank
        required:
            - type
            - title
            - status
            - detail
    ParamError:
        title: ParamError
        type: object
        properties:
            detail:
                type: string
                description: The detail field describes the error.
                example: The 'docKey' field is required.
            parameter:
                type: string
                description: The parameter field contains the name of the parameter that caused the error.
                example: docKey
        description: ParamError represents an error related to a specific request parameter.
        example:
            detail: The 'docKey' field is required.
            parameter: docKey
    UnauthorizedError:
        title: UnauthorizedError
        type: object
        properties:
            detail:
                type: string
                description: The detail field contains a human-readable explanation specific to this problem occurrence.
                example: The request body is missing the docKey field.
            instance:
                type: string
                description: The instance field contains a URI reference that identifies this problem occurrence.
            status:
                type: integer
                description: The status field contains the HTTP status code generated by the origin server.
                example: 400
                format: int32
            title:
                type: string
                description: The title field contains a short, human-readable summary of the problem type.
                example: Invalid request parameters.
            type:
                type: string
                description: The type field contains a URI reference that identifies the problem type.
                default: about:blank
                example: about:blank
                format: uri
        example:
            detail: The request body is missing the docKey field.
            status: 400
            title: Invalid request parameters.
            type: about:blank
        required:
            - type
            - title
            - status
            - detail
securityDefinitions:
    bearer_header_Authorization:
        type: apiKey
        description: 'Authenticate with an access token supplied as Authorization: Bearer [token]. Clients obtain tokens from an external OIDC provider.'
        name: Authorization
        in: header
