// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/artefactual-sdps/sfa-enduro-workflows/internal/actapro (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -typed -destination=./internal/actapro/fake/mock_client.go -package=fake github.com/artefactual-sdps/sfa-enduro-workflows/internal/actapro Client
//

// Package fake is a generated GoMock package.
package fake

import (
	context "context"
	reflect "reflect"

	gen "github.com/artefactual-sdps/sfa-enduro-workflows/internal/actapro/gen"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateMassOperationExport mocks base method.
func (m *MockClient) CreateMassOperationExport(ctx context.Context, request *gen.ExportParamsDTO) (gen.CreateMassOperationExportRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMassOperationExport", ctx, request)
	ret0, _ := ret[0].(gen.CreateMassOperationExportRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMassOperationExport indicates an expected call of CreateMassOperationExport.
func (mr *MockClientMockRecorder) CreateMassOperationExport(ctx, request any) *MockClientCreateMassOperationExportCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMassOperationExport", reflect.TypeOf((*MockClient)(nil).CreateMassOperationExport), ctx, request)
	return &MockClientCreateMassOperationExportCall{Call: call}
}

// MockClientCreateMassOperationExportCall wrap *gomock.Call
type MockClientCreateMassOperationExportCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientCreateMassOperationExportCall) Return(arg0 gen.CreateMassOperationExportRes, arg1 error) *MockClientCreateMassOperationExportCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientCreateMassOperationExportCall) Do(f func(context.Context, *gen.ExportParamsDTO) (gen.CreateMassOperationExportRes, error)) *MockClientCreateMassOperationExportCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientCreateMassOperationExportCall) DoAndReturn(f func(context.Context, *gen.ExportParamsDTO) (gen.CreateMassOperationExportRes, error)) *MockClientCreateMassOperationExportCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDocument mocks base method.
func (m *MockClient) GetDocument(ctx context.Context, params gen.GetDocumentParams) (gen.GetDocumentRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocument", ctx, params)
	ret0, _ := ret[0].(gen.GetDocumentRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocument indicates an expected call of GetDocument.
func (mr *MockClientMockRecorder) GetDocument(ctx, params any) *MockClientGetDocumentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocument", reflect.TypeOf((*MockClient)(nil).GetDocument), ctx, params)
	return &MockClientGetDocumentCall{Call: call}
}

// MockClientGetDocumentCall wrap *gomock.Call
type MockClientGetDocumentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetDocumentCall) Return(arg0 gen.GetDocumentRes, arg1 error) *MockClientGetDocumentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetDocumentCall) Do(f func(context.Context, gen.GetDocumentParams) (gen.GetDocumentRes, error)) *MockClientGetDocumentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetDocumentCall) DoAndReturn(f func(context.Context, gen.GetDocumentParams) (gen.GetDocumentRes, error)) *MockClientGetDocumentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetExportFile mocks base method.
func (m *MockClient) GetExportFile(ctx context.Context, params gen.GetExportFileParams) (gen.GetExportFileRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExportFile", ctx, params)
	ret0, _ := ret[0].(gen.GetExportFileRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExportFile indicates an expected call of GetExportFile.
func (mr *MockClientMockRecorder) GetExportFile(ctx, params any) *MockClientGetExportFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExportFile", reflect.TypeOf((*MockClient)(nil).GetExportFile), ctx, params)
	return &MockClientGetExportFileCall{Call: call}
}

// MockClientGetExportFileCall wrap *gomock.Call
type MockClientGetExportFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetExportFileCall) Return(arg0 gen.GetExportFileRes, arg1 error) *MockClientGetExportFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetExportFileCall) Do(f func(context.Context, gen.GetExportFileParams) (gen.GetExportFileRes, error)) *MockClientGetExportFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetExportFileCall) DoAndReturn(f func(context.Context, gen.GetExportFileParams) (gen.GetExportFileRes, error)) *MockClientGetExportFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetMassOperationInfo mocks base method.
func (m *MockClient) GetMassOperationInfo(ctx context.Context, params gen.GetMassOperationInfoParams) (gen.GetMassOperationInfoRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMassOperationInfo", ctx, params)
	ret0, _ := ret[0].(gen.GetMassOperationInfoRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMassOperationInfo indicates an expected call of GetMassOperationInfo.
func (mr *MockClientMockRecorder) GetMassOperationInfo(ctx, params any) *MockClientGetMassOperationInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMassOperationInfo", reflect.TypeOf((*MockClient)(nil).GetMassOperationInfo), ctx, params)
	return &MockClientGetMassOperationInfoCall{Call: call}
}

// MockClientGetMassOperationInfoCall wrap *gomock.Call
type MockClientGetMassOperationInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetMassOperationInfoCall) Return(arg0 gen.GetMassOperationInfoRes, arg1 error) *MockClientGetMassOperationInfoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetMassOperationInfoCall) Do(f func(context.Context, gen.GetMassOperationInfoParams) (gen.GetMassOperationInfoRes, error)) *MockClientGetMassOperationInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetMassOperationInfoCall) DoAndReturn(f func(context.Context, gen.GetMassOperationInfoParams) (gen.GetMassOperationInfoRes, error)) *MockClientGetMassOperationInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetMassOperationLogs mocks base method.
func (m *MockClient) GetMassOperationLogs(ctx context.Context, params gen.GetMassOperationLogsParams) (gen.GetMassOperationLogsRes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMassOperationLogs", ctx, params)
	ret0, _ := ret[0].(gen.GetMassOperationLogsRes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMassOperationLogs indicates an expected call of GetMassOperationLogs.
func (mr *MockClientMockRecorder) GetMassOperationLogs(ctx, params any) *MockClientGetMassOperationLogsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMassOperationLogs", reflect.TypeOf((*MockClient)(nil).GetMassOperationLogs), ctx, params)
	return &MockClientGetMassOperationLogsCall{Call: call}
}

// MockClientGetMassOperationLogsCall wrap *gomock.Call
type MockClientGetMassOperationLogsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientGetMassOperationLogsCall) Return(arg0 gen.GetMassOperationLogsRes, arg1 error) *MockClientGetMassOperationLogsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientGetMassOperationLogsCall) Do(f func(context.Context, gen.GetMassOperationLogsParams) (gen.GetMassOperationLogsRes, error)) *MockClientGetMassOperationLogsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientGetMassOperationLogsCall) DoAndReturn(f func(context.Context, gen.GetMassOperationLogsParams) (gen.GetMassOperationLogsRes, error)) *MockClientGetMassOperationLogsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
