// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/enums"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/persistence/ent/db/dip"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/persistence/ent/db/predicate"
)

// DIPUpdate is the builder for updating DIP entities.
type DIPUpdate struct {
	config
	hooks    []Hook
	mutation *DIPMutation
}

// Where appends a list predicates to the DIPUpdate builder.
func (_u *DIPUpdate) Where(ps ...predicate.DIP) *DIPUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DIPUpdate) SetStatus(v enums.DIPStatus) *DIPUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DIPUpdate) SetNillableStatus(v *enums.DIPStatus) *DIPUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DIPUpdate) SetErrorMessage(v string) *DIPUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DIPUpdate) SetNillableErrorMessage(v *string) *DIPUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DIPUpdate) ClearErrorMessage() *DIPUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DIPUpdate) SetStartedAt(v time.Time) *DIPUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DIPUpdate) SetNillableStartedAt(v *time.Time) *DIPUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *DIPUpdate) ClearStartedAt() *DIPUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *DIPUpdate) SetCompletedAt(v time.Time) *DIPUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *DIPUpdate) SetNillableCompletedAt(v *time.Time) *DIPUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *DIPUpdate) ClearCompletedAt() *DIPUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *DIPUpdate) SetObjectKey(v string) *DIPUpdate {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *DIPUpdate) SetNillableObjectKey(v *string) *DIPUpdate {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// ClearObjectKey clears the value of the "object_key" field.
func (_u *DIPUpdate) ClearObjectKey() *DIPUpdate {
	_u.mutation.ClearObjectKey()
	return _u
}

// Mutation returns the DIPMutation object of the builder.
func (_u *DIPUpdate) Mutation() *DIPMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DIPUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DIPUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DIPUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DIPUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DIPUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := dip.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`db: validator failed for field "DIP.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DIPUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dip.Table, dip.Columns, sqlgraph.NewFieldSpec(dip.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dip.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(dip.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(dip.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(dip.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(dip.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(dip.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(dip.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(dip.FieldObjectKey, field.TypeString, value)
	}
	if _u.mutation.ObjectKeyCleared() {
		_spec.ClearField(dip.FieldObjectKey, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dip.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DIPUpdateOne is the builder for updating a single DIP entity.
type DIPUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DIPMutation
}

// SetStatus sets the "status" field.
func (_u *DIPUpdateOne) SetStatus(v enums.DIPStatus) *DIPUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DIPUpdateOne) SetNillableStatus(v *enums.DIPStatus) *DIPUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DIPUpdateOne) SetErrorMessage(v string) *DIPUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DIPUpdateOne) SetNillableErrorMessage(v *string) *DIPUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DIPUpdateOne) ClearErrorMessage() *DIPUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DIPUpdateOne) SetStartedAt(v time.Time) *DIPUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DIPUpdateOne) SetNillableStartedAt(v *time.Time) *DIPUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *DIPUpdateOne) ClearStartedAt() *DIPUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *DIPUpdateOne) SetCompletedAt(v time.Time) *DIPUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *DIPUpdateOne) SetNillableCompletedAt(v *time.Time) *DIPUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *DIPUpdateOne) ClearCompletedAt() *DIPUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetObjectKey sets the "object_key" field.
func (_u *DIPUpdateOne) SetObjectKey(v string) *DIPUpdateOne {
	_u.mutation.SetObjectKey(v)
	return _u
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_u *DIPUpdateOne) SetNillableObjectKey(v *string) *DIPUpdateOne {
	if v != nil {
		_u.SetObjectKey(*v)
	}
	return _u
}

// ClearObjectKey clears the value of the "object_key" field.
func (_u *DIPUpdateOne) ClearObjectKey() *DIPUpdateOne {
	_u.mutation.ClearObjectKey()
	return _u
}

// Mutation returns the DIPMutation object of the builder.
func (_u *DIPUpdateOne) Mutation() *DIPMutation {
	return _u.mutation
}

// Where appends a list predicates to the DIPUpdate builder.
func (_u *DIPUpdateOne) Where(ps ...predicate.DIP) *DIPUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DIPUpdateOne) Select(field string, fields ...string) *DIPUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DIP entity.
func (_u *DIPUpdateOne) Save(ctx context.Context) (*DIP, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DIPUpdateOne) SaveX(ctx context.Context) *DIP {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DIPUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DIPUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DIPUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := dip.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`db: validator failed for field "DIP.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DIPUpdateOne) sqlSave(ctx context.Context) (_node *DIP, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dip.Table, dip.Columns, sqlgraph.NewFieldSpec(dip.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "DIP.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dip.FieldID)
		for _, f := range fields {
			if !dip.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != dip.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dip.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(dip.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(dip.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(dip.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(dip.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(dip.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(dip.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ObjectKey(); ok {
		_spec.SetField(dip.FieldObjectKey, field.TypeString, value)
	}
	if _u.mutation.ObjectKeyCleared() {
		_spec.ClearField(dip.FieldObjectKey, field.TypeString)
	}
	_node = &DIP{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dip.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
