// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/enums"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/persistence/ent/db/dip"
	"github.com/google/uuid"
)

// DIPCreate is the builder for creating a DIP entity.
type DIPCreate struct {
	config
	mutation *DIPMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (_c *DIPCreate) SetUUID(v uuid.UUID) *DIPCreate {
	_c.mutation.SetUUID(v)
	return _c
}

// SetDocKey sets the "doc_key" field.
func (_c *DIPCreate) SetDocKey(v string) *DIPCreate {
	_c.mutation.SetDocKey(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DIPCreate) SetStatus(v enums.DIPStatus) *DIPCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *DIPCreate) SetErrorMessage(v string) *DIPCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *DIPCreate) SetNillableErrorMessage(v *string) *DIPCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DIPCreate) SetCreatedAt(v time.Time) *DIPCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DIPCreate) SetNillableCreatedAt(v *time.Time) *DIPCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *DIPCreate) SetStartedAt(v time.Time) *DIPCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *DIPCreate) SetNillableStartedAt(v *time.Time) *DIPCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *DIPCreate) SetCompletedAt(v time.Time) *DIPCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *DIPCreate) SetNillableCompletedAt(v *time.Time) *DIPCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetObjectKey sets the "object_key" field.
func (_c *DIPCreate) SetObjectKey(v string) *DIPCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetNillableObjectKey sets the "object_key" field if the given value is not nil.
func (_c *DIPCreate) SetNillableObjectKey(v *string) *DIPCreate {
	if v != nil {
		_c.SetObjectKey(*v)
	}
	return _c
}

// Mutation returns the DIPMutation object of the builder.
func (_c *DIPCreate) Mutation() *DIPMutation {
	return _c.mutation
}

// Save creates the DIP in the database.
func (_c *DIPCreate) Save(ctx context.Context) (*DIP, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DIPCreate) SaveX(ctx context.Context) *DIP {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DIPCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DIPCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DIPCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dip.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DIPCreate) check() error {
	if _, ok := _c.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`db: missing required field "DIP.uuid"`)}
	}
	if _, ok := _c.mutation.DocKey(); !ok {
		return &ValidationError{Name: "doc_key", err: errors.New(`db: missing required field "DIP.doc_key"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`db: missing required field "DIP.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := dip.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`db: validator failed for field "DIP.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "DIP.created_at"`)}
	}
	return nil
}

func (_c *DIPCreate) sqlSave(ctx context.Context) (*DIP, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DIPCreate) createSpec() (*DIP, *sqlgraph.CreateSpec) {
	var (
		_node = &DIP{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dip.Table, sqlgraph.NewFieldSpec(dip.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UUID(); ok {
		_spec.SetField(dip.FieldUUID, field.TypeUUID, value)
		_node.UUID = value
	}
	if value, ok := _c.mutation.DocKey(); ok {
		_spec.SetField(dip.FieldDocKey, field.TypeString, value)
		_node.DocKey = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(dip.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(dip.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dip.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(dip.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(dip.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = value
	}
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(dip.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = value
	}
	return _node, _spec
}

// DIPCreateBulk is the builder for creating many DIP entities in bulk.
type DIPCreateBulk struct {
	config
	err      error
	builders []*DIPCreate
}

// Save creates the DIP entities in the database.
func (_c *DIPCreateBulk) Save(ctx context.Context) ([]*DIP, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DIP, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DIPMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DIPCreateBulk) SaveX(ctx context.Context) []*DIP {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DIPCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DIPCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
