// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/enums"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/persistence/ent/db/dip"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/persistence/ent/db/predicate"
	"github.com/google/uuid"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeDIP = "DIP"
)

// DIPMutation represents an operation that mutates the DIP nodes in the graph.
type DIPMutation struct {
	config
	op            Op
	typ           string
	id            *int
	uuid          *uuid.UUID
	doc_key       *string
	status        *enums.DIPStatus
	error_message *string
	created_at    *time.Time
	started_at    *time.Time
	completed_at  *time.Time
	object_key    *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*DIP, error)
	predicates    []predicate.DIP
}

var _ ent.Mutation = (*DIPMutation)(nil)

// dipOption allows management of the mutation configuration using functional options.
type dipOption func(*DIPMutation)

// newDIPMutation creates new mutation for the DIP entity.
func newDIPMutation(c config, op Op, opts ...dipOption) *DIPMutation {
	m := &DIPMutation{
		config:        c,
		op:            op,
		typ:           TypeDIP,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withDIPID sets the ID field of the mutation.
func withDIPID(id int) dipOption {
	return func(m *DIPMutation) {
		var (
			err   error
			once  sync.Once
			value *DIP
		)
		m.oldValue = func(ctx context.Context) (*DIP, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().DIP.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withDIP sets the old DIP of the mutation.
func withDIP(node *DIP) dipOption {
	return func(m *DIPMutation) {
		m.oldValue = func(context.Context) (*DIP, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m DIPMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m DIPMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("db: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *DIPMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *DIPMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().DIP.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUUID sets the "uuid" field.
func (m *DIPMutation) SetUUID(u uuid.UUID) {
	m.uuid = &u
}

// UUID returns the value of the "uuid" field in the mutation.
func (m *DIPMutation) UUID() (r uuid.UUID, exists bool) {
	v := m.uuid
	if v == nil {
		return
	}
	return *v, true
}

// OldUUID returns the old "uuid" field's value of the DIP entity.
// If the DIP object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DIPMutation) OldUUID(ctx context.Context) (v uuid.UUID, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUUID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUUID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUUID: %w", err)
	}
	return oldValue.UUID, nil
}

// ResetUUID resets all changes to the "uuid" field.
func (m *DIPMutation) ResetUUID() {
	m.uuid = nil
}

// SetDocKey sets the "doc_key" field.
func (m *DIPMutation) SetDocKey(s string) {
	m.doc_key = &s
}

// DocKey returns the value of the "doc_key" field in the mutation.
func (m *DIPMutation) DocKey() (r string, exists bool) {
	v := m.doc_key
	if v == nil {
		return
	}
	return *v, true
}

// OldDocKey returns the old "doc_key" field's value of the DIP entity.
// If the DIP object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DIPMutation) OldDocKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDocKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDocKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDocKey: %w", err)
	}
	return oldValue.DocKey, nil
}

// ResetDocKey resets all changes to the "doc_key" field.
func (m *DIPMutation) ResetDocKey() {
	m.doc_key = nil
}

// SetStatus sets the "status" field.
func (m *DIPMutation) SetStatus(es enums.DIPStatus) {
	m.status = &es
}

// Status returns the value of the "status" field in the mutation.
func (m *DIPMutation) Status() (r enums.DIPStatus, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the DIP entity.
// If the DIP object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DIPMutation) OldStatus(ctx context.Context) (v enums.DIPStatus, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *DIPMutation) ResetStatus() {
	m.status = nil
}

// SetErrorMessage sets the "error_message" field.
func (m *DIPMutation) SetErrorMessage(s string) {
	m.error_message = &s
}

// ErrorMessage returns the value of the "error_message" field in the mutation.
func (m *DIPMutation) ErrorMessage() (r string, exists bool) {
	v := m.error_message
	if v == nil {
		return
	}
	return *v, true
}

// OldErrorMessage returns the old "error_message" field's value of the DIP entity.
// If the DIP object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DIPMutation) OldErrorMessage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldErrorMessage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldErrorMessage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldErrorMessage: %w", err)
	}
	return oldValue.ErrorMessage, nil
}

// ClearErrorMessage clears the value of the "error_message" field.
func (m *DIPMutation) ClearErrorMessage() {
	m.error_message = nil
	m.clearedFields[dip.FieldErrorMessage] = struct{}{}
}

// ErrorMessageCleared returns if the "error_message" field was cleared in this mutation.
func (m *DIPMutation) ErrorMessageCleared() bool {
	_, ok := m.clearedFields[dip.FieldErrorMessage]
	return ok
}

// ResetErrorMessage resets all changes to the "error_message" field.
func (m *DIPMutation) ResetErrorMessage() {
	m.error_message = nil
	delete(m.clearedFields, dip.FieldErrorMessage)
}

// SetCreatedAt sets the "created_at" field.
func (m *DIPMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *DIPMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the DIP entity.
// If the DIP object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DIPMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *DIPMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetStartedAt sets the "started_at" field.
func (m *DIPMutation) SetStartedAt(t time.Time) {
	m.started_at = &t
}

// StartedAt returns the value of the "started_at" field in the mutation.
func (m *DIPMutation) StartedAt() (r time.Time, exists bool) {
	v := m.started_at
	if v == nil {
		return
	}
	return *v, true
}

// OldStartedAt returns the old "started_at" field's value of the DIP entity.
// If the DIP object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DIPMutation) OldStartedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStartedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStartedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartedAt: %w", err)
	}
	return oldValue.StartedAt, nil
}

// ClearStartedAt clears the value of the "started_at" field.
func (m *DIPMutation) ClearStartedAt() {
	m.started_at = nil
	m.clearedFields[dip.FieldStartedAt] = struct{}{}
}

// StartedAtCleared returns if the "started_at" field was cleared in this mutation.
func (m *DIPMutation) StartedAtCleared() bool {
	_, ok := m.clearedFields[dip.FieldStartedAt]
	return ok
}

// ResetStartedAt resets all changes to the "started_at" field.
func (m *DIPMutation) ResetStartedAt() {
	m.started_at = nil
	delete(m.clearedFields, dip.FieldStartedAt)
}

// SetCompletedAt sets the "completed_at" field.
func (m *DIPMutation) SetCompletedAt(t time.Time) {
	m.completed_at = &t
}

// CompletedAt returns the value of the "completed_at" field in the mutation.
func (m *DIPMutation) CompletedAt() (r time.Time, exists bool) {
	v := m.completed_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCompletedAt returns the old "completed_at" field's value of the DIP entity.
// If the DIP object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DIPMutation) OldCompletedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCompletedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCompletedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCompletedAt: %w", err)
	}
	return oldValue.CompletedAt, nil
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (m *DIPMutation) ClearCompletedAt() {
	m.completed_at = nil
	m.clearedFields[dip.FieldCompletedAt] = struct{}{}
}

// CompletedAtCleared returns if the "completed_at" field was cleared in this mutation.
func (m *DIPMutation) CompletedAtCleared() bool {
	_, ok := m.clearedFields[dip.FieldCompletedAt]
	return ok
}

// ResetCompletedAt resets all changes to the "completed_at" field.
func (m *DIPMutation) ResetCompletedAt() {
	m.completed_at = nil
	delete(m.clearedFields, dip.FieldCompletedAt)
}

// SetObjectKey sets the "object_key" field.
func (m *DIPMutation) SetObjectKey(s string) {
	m.object_key = &s
}

// ObjectKey returns the value of the "object_key" field in the mutation.
func (m *DIPMutation) ObjectKey() (r string, exists bool) {
	v := m.object_key
	if v == nil {
		return
	}
	return *v, true
}

// OldObjectKey returns the old "object_key" field's value of the DIP entity.
// If the DIP object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *DIPMutation) OldObjectKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldObjectKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldObjectKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldObjectKey: %w", err)
	}
	return oldValue.ObjectKey, nil
}

// ClearObjectKey clears the value of the "object_key" field.
func (m *DIPMutation) ClearObjectKey() {
	m.object_key = nil
	m.clearedFields[dip.FieldObjectKey] = struct{}{}
}

// ObjectKeyCleared returns if the "object_key" field was cleared in this mutation.
func (m *DIPMutation) ObjectKeyCleared() bool {
	_, ok := m.clearedFields[dip.FieldObjectKey]
	return ok
}

// ResetObjectKey resets all changes to the "object_key" field.
func (m *DIPMutation) ResetObjectKey() {
	m.object_key = nil
	delete(m.clearedFields, dip.FieldObjectKey)
}

// Where appends a list predicates to the DIPMutation builder.
func (m *DIPMutation) Where(ps ...predicate.DIP) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the DIPMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *DIPMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.DIP, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *DIPMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *DIPMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (DIP).
func (m *DIPMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *DIPMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.uuid != nil {
		fields = append(fields, dip.FieldUUID)
	}
	if m.doc_key != nil {
		fields = append(fields, dip.FieldDocKey)
	}
	if m.status != nil {
		fields = append(fields, dip.FieldStatus)
	}
	if m.error_message != nil {
		fields = append(fields, dip.FieldErrorMessage)
	}
	if m.created_at != nil {
		fields = append(fields, dip.FieldCreatedAt)
	}
	if m.started_at != nil {
		fields = append(fields, dip.FieldStartedAt)
	}
	if m.completed_at != nil {
		fields = append(fields, dip.FieldCompletedAt)
	}
	if m.object_key != nil {
		fields = append(fields, dip.FieldObjectKey)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *DIPMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case dip.FieldUUID:
		return m.UUID()
	case dip.FieldDocKey:
		return m.DocKey()
	case dip.FieldStatus:
		return m.Status()
	case dip.FieldErrorMessage:
		return m.ErrorMessage()
	case dip.FieldCreatedAt:
		return m.CreatedAt()
	case dip.FieldStartedAt:
		return m.StartedAt()
	case dip.FieldCompletedAt:
		return m.CompletedAt()
	case dip.FieldObjectKey:
		return m.ObjectKey()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *DIPMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case dip.FieldUUID:
		return m.OldUUID(ctx)
	case dip.FieldDocKey:
		return m.OldDocKey(ctx)
	case dip.FieldStatus:
		return m.OldStatus(ctx)
	case dip.FieldErrorMessage:
		return m.OldErrorMessage(ctx)
	case dip.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case dip.FieldStartedAt:
		return m.OldStartedAt(ctx)
	case dip.FieldCompletedAt:
		return m.OldCompletedAt(ctx)
	case dip.FieldObjectKey:
		return m.OldObjectKey(ctx)
	}
	return nil, fmt.Errorf("unknown DIP field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DIPMutation) SetField(name string, value ent.Value) error {
	switch name {
	case dip.FieldUUID:
		v, ok := value.(uuid.UUID)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUUID(v)
		return nil
	case dip.FieldDocKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDocKey(v)
		return nil
	case dip.FieldStatus:
		v, ok := value.(enums.DIPStatus)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case dip.FieldErrorMessage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetErrorMessage(v)
		return nil
	case dip.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case dip.FieldStartedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartedAt(v)
		return nil
	case dip.FieldCompletedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCompletedAt(v)
		return nil
	case dip.FieldObjectKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetObjectKey(v)
		return nil
	}
	return fmt.Errorf("unknown DIP field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *DIPMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *DIPMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *DIPMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown DIP numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *DIPMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(dip.FieldErrorMessage) {
		fields = append(fields, dip.FieldErrorMessage)
	}
	if m.FieldCleared(dip.FieldStartedAt) {
		fields = append(fields, dip.FieldStartedAt)
	}
	if m.FieldCleared(dip.FieldCompletedAt) {
		fields = append(fields, dip.FieldCompletedAt)
	}
	if m.FieldCleared(dip.FieldObjectKey) {
		fields = append(fields, dip.FieldObjectKey)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *DIPMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *DIPMutation) ClearField(name string) error {
	switch name {
	case dip.FieldErrorMessage:
		m.ClearErrorMessage()
		return nil
	case dip.FieldStartedAt:
		m.ClearStartedAt()
		return nil
	case dip.FieldCompletedAt:
		m.ClearCompletedAt()
		return nil
	case dip.FieldObjectKey:
		m.ClearObjectKey()
		return nil
	}
	return fmt.Errorf("unknown DIP nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *DIPMutation) ResetField(name string) error {
	switch name {
	case dip.FieldUUID:
		m.ResetUUID()
		return nil
	case dip.FieldDocKey:
		m.ResetDocKey()
		return nil
	case dip.FieldStatus:
		m.ResetStatus()
		return nil
	case dip.FieldErrorMessage:
		m.ResetErrorMessage()
		return nil
	case dip.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case dip.FieldStartedAt:
		m.ResetStartedAt()
		return nil
	case dip.FieldCompletedAt:
		m.ResetCompletedAt()
		return nil
	case dip.FieldObjectKey:
		m.ResetObjectKey()
		return nil
	}
	return fmt.Errorf("unknown DIP field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *DIPMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *DIPMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *DIPMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *DIPMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *DIPMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *DIPMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *DIPMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown DIP unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *DIPMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown DIP edge %s", name)
}
