// Code generated by ent, DO NOT EDIT.

package db

import (
	"time"

	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/persistence/ent/db/dip"
	"github.com/artefactual-sdps/sfa-enduro-workflows/internal/dips/persistence/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dipFields := schema.DIP{}.Fields()
	_ = dipFields
	// dipDescCreatedAt is the schema descriptor for created_at field.
	dipDescCreatedAt := dipFields[4].Descriptor()
	// dip.DefaultCreatedAt holds the default value on creation for the created_at field.
	dip.DefaultCreatedAt = dipDescCreatedAt.Default.(func() time.Time)
}
