// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DipColumns holds the columns for the "dip" table.
	DipColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uuid", Type: field.TypeUUID, Unique: true},
		{Name: "doc_key", Type: field.TypeString, Size: 1024},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"queued", "in progress", "done", "failed"}},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "object_key", Type: field.TypeString, Nullable: true, Size: 1024},
	}
	// DipTable holds the schema information for the "dip" table.
	DipTable = &schema.Table{
		Name:       "dip",
		Columns:    DipColumns,
		PrimaryKey: []*schema.Column{DipColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DipTable,
	}
)

func init() {
	DipTable.Annotation = &entsql.Annotation{
		Table: "dip",
	}
}
