apiVersion: v1
kind: Secret
metadata:
  name: sfa-dips-secret
type: Opaque
stringData:
  sfa-dips.toml: |
    # logFormat controls the encoding of application log messages. Supported
    # values are "json" for structured output and "text" for human-readable,
    # colorized output.
    logFormat = "text"
    # verbosity supports values from 0-128, with 0 as least verbose and 128
    # capturing all possible log events.
    verbosity = 2

    [api]
    # Address of the API server.
    listen = ":8080"

    # CORS Access-Control-Allow-Origin policy for the API server. Defaults to the
    # listen address if not set.
    corsOrigin = "*"

    [api.log]
    # Path to the API log file. Accepts stdout or stderr for console output. If
    # `path` is not set, or set to an empty string, logging is disabled.
    path = "stdout"

    # Log level sets the log verbosity. Valid values are: "debug", "info" (default),
    # "warn", and "error" (case-insensitive).
    level = "warn"

    # Format of the log messages. Valid values are: "json" (default) and "text".
    format = "text"

    [persistence]
    driver = "mysql"
    dsn = ""
    migrate = true
