apiVersion: v1
kind: Secret
metadata:
  name: sfa-dips-secret
type: Opaque
stringData:
  sfa-dips.toml: |
    debug = true
    verbosity = 2

    [api]
    listen = ":8080"
    debug = true
    corsOrigin = "*"
